version: "3.9"
services:
  nodejs:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongodb
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example