# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI


on:
  workflow_dispatch:
  schedule:
    - cron: '0/10 * * * *' 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      env: 
        MYTOKEN: ${{secrets.MYTOKEN}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo apt install -y git
    - run: sudo apt install -y openjdk-17-jdk
    - run: npm install -g sass
    - run: sudo chmod -R a+rwx src/gradle_build.sh
    - run: sudo chmod -R a+rwx src/commit_build.sh
    - run: sudo chmod -R a+rwx src/commit_static_files.sh
    - run: npm ci
    - run: MYTOKEN=${{secrets.MYTOKEN}} npm run start
